- name: get the user homedir
  getent:
    database: passwd
    key: "{{ user.name }}"
- name: update user file
  include_tasks: "user_files/update_lineinfile.yml"
  with_items: "{{ user.user_lineinfiles | default([]) }}"
  loop_control:
    loop_var: user_lineinfile
